server:
  port: 8100
  servlet:
    context-path: /admin

#数据库配置
jdbc:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capricorn?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useAffectedRows=true&serverTimezone=UTC
    username: root
    password: 123
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml

#http请求配置
http:
  readTimeout: 8000
  connectTimeout: 8000